version: "3.8"

services:
  litellm:
    image: ghcr.io/berriai/litellm:main-stable

    volumes:
      - litellm_config:/app/config
      - postgres_data:/var/lib/postgresql/data

    command:
      - "--config=/app/config/config.yaml"

    ports:
      - "4050:4000"

    env_file:
      - .env

    environment:
      DATABASE_URL: "${DATABASE_URL}"
      STORE_MODEL_IN_DB: "True"

    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    container_name: litellm_db

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  litellm_config:
    external: true   # Coolify volume you will create
  postgres_data:
    name: litellm_postgres_data
